### PR TITLE
Improved Load Store Optimization

### PR DESCRIPTION
**Pull request by hediet**
- [x] Constant Folding of pointer comparison when pointers are disjoint
- [x] Node propagation

### CODE REVIEW

**Comment by problame** [comment]
Sorry, pushed to this branch yesterday for #228  , feel free to drop my commits

**Comment by reiner-dolp** [comment]
What's a "cmp optimization"?

Drop christians commits using `git reset HEAD~3`

**Comment by hediet** [comment]
> What's a "cmp optimization"?
`a == null` ist false, wenn `a` niemals null sein kann. Die Optimierung erkennt sowas.

**Comment by flip1995** [comment]
bors r=flip1995

**Pull request merged**
