### PR TITLE
implement visitor based on pattern matching

### PR DESCRIPTION
**Pull request by problame**
this PR is the basis for the prettyprinting PR https://github.com/comprakt/comprakt/pull/50

### CODE REVIEW

**Comment by joshuabach** [comment]
This seems to have been tested (at least on basically) by the prettyprinter in #50. So I guess merge?

**Comment by reiner-dolp** [comment]
- [ ] the cli flag is incorrectly named, should be "--print-ast". But that is fixed by the pretty printer branch
- [ ] structureprint.rs and prettyprint.rs not being in a subfolder "print/{structure, pretty}.rs" seems weird. Namespaces would make more sense to: `print::structure::Printer` and `print::pretty::Printer`.

**Comment by reiner-dolp** [comment]
See my notes above, but I would like to go ahead and merge it anways.

**Pull request merged**
