### PR TITLE
update phil's test in PR #32

### PR DESCRIPTION
**Pull request by reiner-dolp**
@flip1995 this seems fixed?

### CODE REVIEW

**Comment by flip1995** [comment]
I don't think so, will test it in a bit

**Comment by flip1995** [comment]
```
thread 'parser::tests::phase2_tests::invalid_double_keyword_local_var' panicked at 'assertion failed: `(left == right)`
  left: `"keyword \'void\'"`,
 right: `"do"`', src/parser.rs:1078:17
```

**Comment by problame** [comment]
@flip1995 is this one still relevant?

**Comment by flip1995** [comment]
Yes

**Comment by flip1995** [comment]
> @flip1995 this seems fixed?

Seems @reiner-dolp was right and this was already fixed.

**Pull request closed without merging**
