### PR TITLE
Add attributed grammar and abstract syntax

### PR DESCRIPTION
**Pull request by joshuabach**

### CODE REVIEW

**Comment by reiner-dolp** [comment]
Shouldn't both be moved into the tasksheets/sheet2/ subfolder?

**Comment by joshuabach** [comment]
At least the `grammer.md` is not only for any specific assignment, but also a documentation of our code. As it (fairly) resembles what is implemented in parser.rs

**Comment by problame** [comment]
bors try

**Comment by problame** [comment]
bors r=flip1995,problame

**Pull request merged**
