### PR TITLE
freeze behavior not covered by unit tests (UB + main method)

### PR DESCRIPTION
**Pull request by problame**

### CODE REVIEW

**Comment by flip1995** [comment]
I wouldn't "freeze" 8fc3cb6, since the Error can/should be approved. Everything else LGTM.

**Comment by problame** [comment]
I linked to issue #106 in the commit...

**Comment by reiner-dolp** [comment]
I agree with problame, we have merged incorrect results before to ensure they are tracked during development.

**Comment by reiner-dolp** [comment]
@problame If you don't want to amend a few other tests, you can `bors r=reiner-dolp,flip1995`

**Comment by flip1995** [comment]
bors r=flip1995,reiner-dolp

**Pull request merged**
