### PR TITLE
add `--lower` cli command for firm/assembler phase

### PR DESCRIPTION
**Pull request by reiner-dolp**
- integration tests will use this command for interfacing until the required command is released in next weeks assignment

### CODE REVIEW

**Comment by joshuabach** [comment]
Technically, `--assemble` is the wrong name for this option. The process of "assembling" is converting assemblercode to machinecode (That's why the program doing it is called the *(GNU) assembler*). :trollface: I don't know if there's a good name for just producing assemblercode :-)

**Comment by flip1995** [comment]
`--lower`

**Comment by joshuabach** [comment]
> Oh we need to link the libfirm.so lib

If I'm not mistaken, waiting for problam/play-libfirm to be in a mergable state and then rebasing on that should suffice to resolve all build problems, right? At least `./run` works over there (doesn't work here)

**Comment by flip1995** [comment]
cherry-picked in ontop of this. I want to move forward with this.

bors r+

**Pull request merged**
